from django.conf.urls import patterns, url

from books.views.author_views import *
urlpatterns = patterns('',
    url(
        regex=r'^author/archive/$',
        view=AuthorArchiveIndexView.as_view(),
        name='books_author_archive_index'
    ),
    url(
        regex=r'^author/create/$',
        view=AuthorCreateView.as_view(),
        name='books_author_create'
    ),
    url(
        regex=r'^author/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=AuthorDateDetailView.as_view(),
        name='books_author_date_detail'
    ),
    url(
        regex=r'^author/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=AuthorDayArchiveView.as_view(),
        name='books_author_day_archive'
    ),
    url(
        regex=r'^author/(?P<pk>\d+?)/delete/$',
        view=AuthorDeleteView.as_view(),
        name='books_author_delete'
    ),
    url(
        regex=r'^author/(?P<pk>\d+?)/$',
        view=AuthorDetailView.as_view(),
        name='books_author_detail'
    ),
    url(
        regex=r'^author/$',
        view=AuthorListView.as_view(),
        name='books_author_list'
    ),
    url(
        regex=r'^author/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=AuthorMonthArchiveView.as_view(),
        name='books_author_month_archive'
    ),
    url(
        regex=r'^author/today/$',
        view=AuthorTodayArchiveView.as_view(),
        name='books_author_today_archive'
    ),
    url(
        regex=r'^author/(?P<pk>\d+?)/update/$',
        view=AuthorUpdateView.as_view(),
        name='books_author_update'
    ),
    url(
        regex=r'^author/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=AuthorWeekArchiveView.as_view(),
        name='books_author_week_archive'
    ),
    url(
        regex=r'^author/archive/(?P<year>\d{4})/$',
        view=AuthorYearArchiveView.as_view(),
        name='books_author_year_archive'
    ),
)
